// Import Libraries
import Head from "next/head";
import { getData } from "../../utils/fetchData";

// Import Components
import Header from "../../components/HeaderPage";
import CardEventSection from "../../components/CardEvent";
import StoriesSection from "../../components/Stories";
import StatisticsSection from "../../components/Statistics";
import Footer from "../../components/Footer";
import DetailPage from "../../components/DetailPage";
import Navbar from "../../components/Navbar";

export default function DetailEventPage({ data }) {
  return (
    <>
      <Head>
        <title>Semina || Details Event</title>
        <meta name="description" content="Generated by create Next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header v1 */}
      {/* <Header detail /> */}

      {/* Header v2 */}
      <section className="bg-navy">
        <Navbar />
      </section>

      {/* Detail Content Section */}
      <DetailPage data={data} />

      {/* Grow Today Section */}
      <CardEventSection data={[]} subtitle="Next One" title="Similiar Events" />

      {/* Stories Section */}
      <StoriesSection />

      {/* Statistics Section */}
      <StatisticsSection />

      {/* Footer */}
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  // Fetch API
  const reqServer = await getData(`api/v1/participants/detail-page/${context.params.id}`),
    res = reqServer.data;

  return { props: { data: res } };
}
