// Import Libraries
import Head from "next/head";
import { useRouter } from "next/router";

// Import Components
import Header from "../../components/HeaderPage";
import BrandSection from "../../components/Brand";
import CardEventSection from "../../components/CardEvent";
import StoriesSection from "../../components/Stories";
import StatisticsSection from "../../components/Statistics";
import Footer from "../../components/Footer";
import DetailPage from "../../components/DetailPage";

export default function DetailEventPage() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Semina || Details Event</title>
        <meta name="description" content="Generated by create Next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header detail />

      {/* Detail Content Section */}
      <DetailPage />

      {/* Grow Today Section */}
      <CardEventSection data={[]} subtitle="Next One" title="Similiar Events" />

      {/* Stories Section */}
      <StoriesSection />

      {/* Statistics Section */}
      <StatisticsSection />

      {/* Footer */}
      <Footer />
    </>
  );
}
