// Import Libraries
import Head from "next/head";
import { getData } from "../../utils/fetchData";

// Import Components
import Header from "../../components/HeaderPage";
import CardEventSection from "../../components/CardEvent";
import StoriesSection from "../../components/Stories";
import StatisticsSection from "../../components/Statistics";
import Footer from "../../components/Footer";
import DetailPage from "../../components/DetailPage";
import Navbar from "../../components/Navbar";
import { useEffect, useState } from "react";

export default function DetailEventPage({ dataDetail }) {
  const [data, setData] = useState([]);

  // Fetch API Landing
  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await getData("api/v1/participants/landing-page");

        setData(res.data);
      } catch (err) {}
    };
    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Semina || Details Event</title>
        <meta name="description" content="Generated by create Next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header v1 */}
      {/* <Header detail /> */}

      {/* Header v2 */}
      <section className="bg-navy">
        <Navbar />
      </section>

      {/* Detail Content Section */}
      <DetailPage data={dataDetail} />

      {/* Grow Today Section */}
      <CardEventSection data={data} subtitle="Next One" title="Similiar Events" />

      {/* Stories Section */}
      <StoriesSection />

      {/* Statistics Section */}
      <StatisticsSection />

      {/* Footer */}
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  // Fetch API Detail
  const reqDetail = await getData(`api/v1/participants/detail-page/${context.params.id}`),
    resDetail = reqDetail.data;

  return { props: { dataDetail: resDetail } };
}
