import Head from "next/head";

// Import Components
import Header from "../components/HeaderPage";
import CheckoutSection from "../components/CheckoutPage";
import Footer from "../components/Footer";

export default function Checkout() {
  return (
    <>
      <Head>
        <title>Semina || Checkout Event</title>
        <meta name="description" content="Generated by create Next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header checkout />

      {/* Checkout */}
      <CheckoutSection />

      {/* Footer */}
      <Footer />
    </>
  );
}
