// Import Libraries
import Head from "next/head";

// Import Components
import Header from "../components/HeaderPage";
import BrandSection from "../components/Brand";
import CardEventSection from "../components/CardEvent";
import StoriesSection from "../components/Stories";
import StatisticsSection from "../components/Statistics";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Semina || Landing Page</title>
        <meta name="description" content="Generated by create Next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Brand Section */}
      <BrandSection landing />

      {/* Grow Today Section */}
      <CardEventSection data={[]} subtitle="Grow Today" title="Featured Events" />

      {/* Stories Section */}
      <StoriesSection />

      {/* Statistics Section */}
      <StatisticsSection />

      {/* Footer */}
      <Footer />
    </>
  );
}
