import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Semina || Landing Page</title>
        <meta name="description" content="Generated by create Next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="header bg-navy">
        {/* <!-- START: NAVBAR --> */}
        <nav className="container navbar navbar-expand-lg navbar-dark">
          <div className="container-fluid">
            <a className="navbar-brand" href="index.html">
              <img src="/images/logo.svg" alt="semina" />
            </a>
            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div className="navbar-nav mx-auto my-3 my-lg-0">
                <a className="nav-link active" aria-current="page" href="index.html">
                  Home
                </a>
                <a className="nav-link" href="#">
                  Browse
                </a>
                <a className="nav-link" href="#">
                  Stories
                </a>
                <a className="nav-link" href="#">
                  About
                </a>
              </div>
              <div className="d-grid">
                <a className="btn-navy" href="signin.html">
                  Sign In
                </a>
              </div>
            </div>
          </div>
        </nav>
        {/* <!-- END: NAVBAR --> */}

        <div className="hero">
          <div className="hero-headline">
            Expand Your <span className="text-gradient-blue">Knowledge</span> <br className="d-none d-lg-block" />
            by <span className="text-gradient-pink">Joining</span> Our Greatest Events
          </div>
          <p className="hero-paragraph">
            Kami menyediakan berbagai acara terbaik untuk membantu <br className="d-none d-lg-block" />
            anda dalam meningkatkan skills di bidang teknologi
          </p>
          <a href="#grow-today" className="btn-green">
            Browse Now
          </a>
        </div>

        <div className="d-flex flex-row flex-nowrap justify-content-center align-items-center gap-5 header-image">
          <img src="/images/1.png" alt="semina" className="img-1" />
          <img src="/images/2.png" alt="semina" className="img-2" />
          <img src="/images/1.png" alt="semina" className="img-1" />
        </div>
      </header>
    </div>
  );
}
