import Head from "next/head";

// Import Components
import Header from "../components/HeaderPage";
import SigninPage from "../components/SigninPage";
import BrandSection from "../components/Brand";
import Navbar from "../components/Navbar";

export default function Signin() {
  return (
    <>
      <Head>
        <title>Semina || Sign In</title>
        <meta name="description" content="Generated by create Next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      <section className="bg-navy">
        {/* <Header signin /> */}
        <Navbar signin />
      </section>

      {/* Form Signin */}
      <SigninPage />

      {/* Brand */}
      <BrandSection />
    </>
  );
}
