import Head from "next/head";
import Cookies from "js-cookie";

// Import Components
import Header from "../components/HeaderPage";
import SigninPage from "../components/SigninPage";
import BrandSection from "../components/Brand";
import Navbar from "../components/Navbar";
import { redirect } from "next/dist/server/api-utils";

export default function Signin() {
  return (
    <>
      <Head>
        <title>Semina || Sign In</title>
        <meta name="description" content="Generated by create Next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      <section className="bg-navy">
        {/* <Header signin /> */}
        <Navbar signin />
      </section>

      {/* Form Signin */}
      <SigninPage />

      {/* Brand */}
      <BrandSection />
    </>
  );
}

// Check Token User
export async function getServerSideProps(context) {
  const { token } = context.req.cookies;

  if (token) {
    return { redirect: { destination: "/", permanent: false } };
  }

  return { props: { data: [] } };
}
