import Head from "next/head";

// Import Components
import Header from "../components/HeaderPage";
import SigninPage from "../components/SigninPage";
import BrandSection from "../components/Brand";

export default function Signin() {
  return (
    <>
      <Head>
        <title>Semina || Sign In</title>
        <meta name="description" content="Generated by create Next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header signin />

      {/* Form Signin */}
      <SigninPage />

      {/* Brand */}
      <BrandSection />
    </>
  );
}
