import Head from "next/head";

// Import Components
import Header from "../components/HeaderPage";
import SignupSection from "../components/SignupPage";
import BrandSection from "../components/Brand";
import Navbar from "../components/Navbar";

export default function Signup() {
  return (
    <>
      <Head>
        <title>Semina || Registration</title>
        <meta name="description" content="Generated by create Next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      {/* <Header signup /> */}
      <section className="bg-navy">
        <Navbar />
      </section>

      {/* Form Signup */}
      <SignupSection />

      {/* Brand */}
      <BrandSection />
    </>
  );
}
