// Import Libraries
import Head from "next/head";
import React from "react";
import DashboardPage from "../../components/Dashboard";
import Footer from "../../components/Footer";

// Import Components
import Navbar from "../../components/Navbar";
import { getData } from "../../utils/fetchData";

export default function Dashboard({ data }) {
  return (
    <>
      <Head>
        <title>Semina || Dashboard</title>
        <meta name="description" content="Generated by create Next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      <section className="bg-navy">
        <Navbar />
      </section>

      {/* Content */}
      <DashboardPage data={data} />

      {/* Footer */}
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  // Check Token User
  const { token } = context.req.cookies;

  if (!token) {
    return { redirect: { destination: "/signin", permanent: false } };
  }

  // Fetch API
  const reqServer = await getData(`api/v1/participants/dashboard`, {}, context.req.cookies.token),
    res = reqServer.data;

  return { props: { data: res } };
}
